[package]
name = "rustic-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5"
builder-server = {git = "https://github.com/sigp/ethereum_apis", rev = "56f0e609b01b11a3e0ebec870e4fe51387dcf1d9"}
ethereum-apis-common= {git = "https://github.com/sigp/ethereum_apis", rev = "56f0e609b01b11a3e0ebec870e4fe51387dcf1d9"}
async-trait = "0.1.51"
tokio = { version = "1", default-features = false, features = ["signal", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = {version = "0.3.8", features = ["env-filter"]}
tracing-error = "0.2.0"
tracing-core = "0.1.21"
async-channel = "1.9.0"
futures-channel = "0.3.21"
axum = { version = "0.7" }
slog = "2.7.0"
tracing-slog = "0.3.0"
hex = "0.4.3"
types = { git = "https://github.com/sigp/lighthouse", rev = "c33307d70287fd3b7a70785f89dadcb737214903" }
eth2 = { git = "https://github.com/sigp/lighthouse", rev = "c33307d70287fd3b7a70785f89dadcb737214903" }
execution_layer = { git = "https://github.com/sigp/lighthouse", rev = "c33307d70287fd3b7a70785f89dadcb737214903" }
task_executor = { git = "https://github.com/sigp/lighthouse", rev = "c33307d70287fd3b7a70785f89dadcb737214903" }
sensitive_url = { git = "https://github.com/sigp/lighthouse", rev = "c33307d70287fd3b7a70785f89dadcb737214903" }
eth2_network_config = { git = "https://github.com/sigp/lighthouse", rev = "c33307d70287fd3b7a70785f89dadcb737214903" }
